version: "3"
services:
   namenode1:
      image: flokkr/hadoop:${VERSION}
      hostname: namenode1
      command: ["hdfs", "namenode"]
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          SLEEP_SECONDS: 20
   namenode2:
      image: flokkr/hadoop:${VERSION}
      hostname: namenode2
      command: ["hdfs", "namenode"]
      ports:
         - 9871:9870
      env_file:
        - ./config
      environment:
          ENSURE_STANDBY_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          SLEEP_SECONDS: 40
   namenode3:
      image: flokkr/hadoop:${VERSION}
      hostname: namenode2
      command: ["hdfs", "namenode"]
      ports:
         - 9872:9870
      env_file:
        - ./config
      environment:
          ENSURE_STANDBY_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
          SLEEP_SECONDS: 40
   journal1:
      image: flokkr/hadoop:${VERSION}
      hostname: journal1
      env_file:
        - ./config
      command: ["hdfs", "journalnode"]
   journal2:
      image: flokkr/hadoop:${VERSION}
      hostname: journal2
      env_file:
        - ./config
      command: ["hdfs", "journalnode"]
   journal3:
      image: flokkr/hadoop:${VERSION}
      hostname: journal3
      env_file:
        - ./config
      command: ["hdfs", "journalnode"]
   datanode1:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      hostname: datanode1
      env_file:
        - ./config
      environment:
         SLEEP_SECONDS: 50
   datanode2:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      hostname: datanode2
      env_file:
        - ./config
      environment:
         SLEEP_SECONDS: 50
   datanode3:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "datanode"]
      hostname: datanode3
      env_file:
        - ./config
      environment:
         SLEEP_SECONDS: 50
   activator:
      image: flokkr/hadoop:${VERSION}
      command: ["hdfs", "haadmin", "-transitionToActive", "nn1"]
      env_file:
        - ./config
      environment:
         SLEEP_SECONDS: 60
