version: "2"
services:
   namenode:
      image: flokkr/hadoop:${HADOOP_VERSION}
      hostname: namenode
      command: ["hdfs","namenode"]
      ports:
         - 9870:9870
      env_file:
        - ./config
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
   datanode:
      image: flokkr/hadoop:${HADOOP_VERSION}
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
   resourcemanager:
      image: flokkr/hadoop:${HADOOP_VERSION}
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./config
   nodemanager:
      image: flokkr/hadoop:${HADOOP_VERSION}
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
   zookeeper:
      image: flokkr/zookeeper
      hostname: zookeeper
      environment:
        ZOO.CFG_clientPort: 2181
        ZOO.CFG_dataDir: /tmp/zookeeper
   metastoredb:
     image: postgres
     environment:
       POSTGRES_PASSWORD: rootpwd
       POSTGRES_DB: metastore
       POSTGRES_USER: hive
   metastore:
     image: flokkr/hive
     command: ["hive","--service", "metastore"]
     env_file:
        - ./config
   hiveserver2:
     image: flokkr/hive
     command: ["hive","--service", "hiveserver2"]
     volumes:
        - ./testdata.sql:/tmp/testdata.sql
     environment:
        HADOOP_CONF_DIR: /opt/hive/conf
     ports:
        - 10002:10002
     env_file:
        - ./config
networks:
   default:
      external:
         name: bigdata

